# Generated by Django 3.2 on 2022-09-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NIDInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bangla', models.CharField(max_length=255)),
                ('name_english', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nid_no', models.CharField(max_length=50)),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='NID_Image_Back/')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='NID_Image_Front/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
