# Generated by Django 3.2 on 2022-09-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authentications', '0001_initial'),
        ('nid_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nidinformation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authentications.user'),
        ),
    ]
