# Generated by Django 3.2 on 2022-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nid_information', '0002_nidinformation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nidinformation',
            name='professions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
