# Generated by Django 3.2 on 2022-12-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nid_information', '0003_nidinformation_professions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nidinformation',
            name='name_bangla',
        ),
    ]
