# Generated by Django 3.2 on 2022-09-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDayCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField()),
                ('date_of_issue_certificate', models.DateField()),
                ('birth_registration_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=300)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('present_address', models.CharField(max_length=300)),
                ('is_verified', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='birthday_certificate/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
