# Generated by Django 3.2 on 2022-11-11 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('birth_day_certificate', '0002_birthdaycertificate_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdaycertificate',
            old_name='nationality',
            new_name='father_nationality',
        ),
        migrations.AddField(
            model_name='birthdaycertificate',
            name='mother_nationality',
            field=models.CharField(default=datetime.datetime(2022, 11, 11, 9, 17, 17, 564599, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
