# Generated by Django 3.2 on 2022-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='passport/'),
        ),
        migrations.AddField(
            model_name='passport',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
