# Generated by Django 3.2 on 2022-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
